In [1]:
# import basic libraries
import pandas as pd
import numpy as np

In [2]:
# import dataset
df = pd.read_csv('MD1.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [3]:
print(X)

[[6.68371997e+03 9.80000000e+01 2.37810000e+02 7.13901150e+02]
 [4.24322510e+03 6.40000000e+01 2.21600000e+01 3.94740830e+02]
 [3.73281641e+03 5.90000000e+01 2.52380000e+02 3.90323120e+02]
 ...
 [2.52787726e+03 5.30000000e+01 3.19400000e+01 2.69669190e+02]
 [3.91534326e+03 9.10000000e+01 6.11400000e+01 4.42000370e+02]
 [2.39136353e+03 5.60000000e+01 5.95000000e+00 2.56509510e+02]]


In [4]:
print(y)

['NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'W' 'W' 'W'
 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W'
 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W'
 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'N

In [5]:
# encode categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [6]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [7]:
# split into training and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [8]:
print(X_train)

[[2516.56104   56.        27.78     234.99802]
 [3809.48547   66.        33.12     452.26889]
 [4264.52734   33.       202.53     400.78256]
 ...
 [2456.69214   56.        35.36     244.16148]
 [3356.46118   54.        20.24     415.55554]
 [3091.22803   55.       139.18     303.77399]]


In [9]:
print(X_test)

[[5.08537329e+03 8.40000000e+01 4.91100000e+01 4.87930950e+02]
 [4.50243408e+03 5.30000000e+01 4.51610010e+02 4.52242800e+02]
 [3.53631073e+03 7.10000000e+01 1.20920000e+02 4.08140450e+02]
 [3.61041669e+03 7.50000000e+01 6.75900000e+01 4.18131240e+02]
 [3.50736646e+03 5.50000000e+01 1.00260000e+02 3.33831090e+02]
 [3.19140259e+03 5.50000000e+01 2.91500000e+01 3.09739320e+02]
 [5.94541211e+03 7.70000000e+01 1.00509000e+03 7.20876220e+02]
 [3.14751147e+03 5.20000000e+01 6.44900000e+01 3.59783290e+02]
 [1.34409814e+03 3.40000000e+01 0.00000000e+00 1.27874410e+02]
 [6.17417480e+03 8.70000000e+01 4.63430010e+02 6.70239320e+02]
 [4.04787964e+03 6.70000000e+01 2.32400000e+01 4.02406490e+02]
 [2.27336792e+03 3.70000000e+01 4.51500000e+01 2.11089660e+02]
 [3.63430609e+03 6.60000000e+01 3.17000000e+01 3.79013530e+02]
 [3.14149609e+03 6.00000000e+01 1.21880000e+02 3.08428290e+02]
 [3.46620035e+03 5.40000000e+01 1.03260000e+02 3.11572460e+02]
 [1.48486145e+03 3.20000000e+01 7.41000000e+00 1.293184

In [10]:
print(y_train)

[0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0
 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1
 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0 1
 1 0 1 0 0 0 1 1 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1
 1 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 1 0
 1 1 0 1 0 0 1 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 0 1 0 1 1 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 1 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 0 1
 1 0 1 0 0 1 1 0]


In [11]:
print(y_test)

[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0
 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0
 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0]


In [12]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
print(X_train)

[[-0.6829839  -0.10800606 -0.48235288 -0.76465965]
 [ 0.20688211  0.38569713 -0.45254487  0.50960681]
 [ 0.52006847 -1.24352342  0.49310611  0.20764593]
 ...
 [-0.72418917 -0.10800606 -0.44004113 -0.71091711]
 [-0.10491563 -0.2067467  -0.52444136  0.2942876 ]
 [-0.28746456 -0.15737638  0.13948478 -0.3612972 ]]


In [14]:
print(X_test)

[[ 1.08502254e+00  1.27436289e+00 -3.63288276e-01  7.18760327e-01]
 [ 6.83809770e-01 -2.56117024e-01  1.88347713e+00  5.09453793e-01]
 [ 1.88673203e-02  6.32548734e-01  3.75569904e-02  2.50799030e-01]
 [ 6.98713651e-02  8.30030013e-01 -2.60132441e-01  3.09393763e-01]
 [-1.05381477e-03 -1.57376384e-01 -7.77676607e-02 -1.85016066e-01]
 [-2.18518582e-01 -1.57376384e-01 -4.74705509e-01 -3.26311282e-01]
 [ 1.67695143e+00  9.28770653e-01  4.97301666e+00  2.08495518e+00]
 [-2.48727011e-01 -3.05487344e-01 -2.77436720e-01 -3.28096613e-02]
 [-1.48994127e+00 -1.19415310e+00 -6.37421558e-01 -1.39292622e+00]
 [ 1.83439926e+00  1.42247385e+00  1.94945667e+00  1.78797610e+00]
 [ 3.70958887e-01  4.35067454e-01 -5.07695281e-01  2.17170072e-01]
 [-8.50363597e-01 -1.04604214e+00 -3.85393097e-01 -9.04879192e-01]
 [ 8.63134438e-02  3.85697134e-01 -4.60471343e-01  7.99732896e-02]
 [-2.52867147e-01  8.94752152e-02  4.29157351e-02 -3.34000309e-01]
 [-2.93867331e-02 -2.06746704e-01 -6.10215836e-02 -3.15560146e

In [15]:
# logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [16]:
# classification model defined
model = LogisticRegression(random_state=0).fit(X, y)

In [17]:
# the intercept 𝑏₀
model.intercept_

array([-1.0852408])

In [18]:
# the slope 𝑏₁
model.coef_

array([[ 6.40149294e-05, -5.83616780e-03,  4.79976402e-04,
         4.97846871e-04]])

In [19]:
# the matrix of probabilities that the predicted output is equal to 0 or 1
model.predict_proba(X)

array([[0.68130396, 0.31869604],
       [0.72710207, 0.27289793],
       [0.70581849, 0.29418151],
       [0.6971104 , 0.3028896 ],
       [0.71685802, 0.28314198],
       [0.73196974, 0.26803026],
       [0.71595428, 0.28404572],
       [0.60478189, 0.39521811],
       [0.7371175 , 0.2628825 ],
       [0.72504723, 0.27495277],
       [0.71737853, 0.28262147],
       [0.73184329, 0.26815671],
       [0.70493109, 0.29506891],
       [0.70467278, 0.29532722],
       [0.71007978, 0.28992022],
       [0.72214341, 0.27785659],
       [0.58853728, 0.41146272],
       [0.69055085, 0.30944915],
       [0.72913366, 0.27086634],
       [0.60216567, 0.39783433],
       [0.68874089, 0.31125911],
       [0.733412  , 0.266588  ],
       [0.72437242, 0.27562758],
       [0.72380683, 0.27619317],
       [0.72900535, 0.27099465],
       [0.74399323, 0.25600677],
       [0.76905288, 0.23094712],
       [0.68822804, 0.31177196],
       [0.73439184, 0.26560816],
       [0.733412  , 0.266588  ],
       [0.

In [20]:
# the actual prediction
model.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [21]:
# model accuracy
model.score(X, y)

0.7209302325581395

In [22]:
# more comprehensive model report
from sklearn.metrics import classification_report
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       0.72      1.00      0.84       342
           1       0.00      0.00      0.00       131

    accuracy                           0.72       473
   macro avg       0.36      0.50      0.42       473
weighted avg       0.52      0.72      0.61       473

