In [23]:
# import basic libraries
import pandas as pd
import numpy as np

In [24]:
# import dataset
df = pd.read_csv('MD2.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [25]:
print(X)

[[2.77436206e+03 4.70000000e+01 1.55050000e+02 2.93725520e+02]
 [2.98927759e+03 5.70000000e+01 4.19900000e+01 2.97868840e+02]
 [5.33473584e+03 7.60000000e+01 6.75840010e+02 6.13325930e+02]
 [3.62208838e+03 6.10000000e+01 1.07980000e+02 3.41315330e+02]
 [3.29321881e+03 5.70000000e+01 5.49400000e+01 3.50613740e+02]
 [2.99986108e+03 5.20000000e+01 1.30610000e+02 3.07239140e+02]
 [3.98283508e+03 7.00000000e+01 1.33220000e+02 3.58224090e+02]
 [2.95064819e+03 3.00000000e+01 1.83509990e+02 3.01365810e+02]
 [8.31595605e+03 1.15000000e+02 5.36870020e+02 8.93366640e+02]
 [3.14984766e+03 6.20000000e+01 5.22700000e+01 2.68277390e+02]
 [3.28475629e+03 6.10000000e+01 5.74700000e+01 3.35960630e+02]
 [3.49922998e+03 6.10000000e+01 5.47700000e+01 4.27846920e+02]
 [3.51765082e+03 7.00000000e+01 1.53310000e+02 3.97983000e+02]
 [3.44261694e+03 6.20000000e+01 3.47400000e+01 3.64999810e+02]
 [3.30998389e+03 6.10000000e+01 1.67900000e+01 3.67440500e+02]
 [4.63446045e+03 8.30000000e+01 6.66500000e+01 5.779132

In [26]:
print(y)

['NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W'
 'W' 'W' 'W' 'W' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'W' 'W' 'W' 'W' 'W' 'W' 'W'
 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W']


In [27]:
# encode categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [28]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [29]:
# split into training and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [30]:
print(X_train)

[[2.85152710e+03 6.00000000e+01 4.75900000e+01 2.08481310e+02]
 [2.32611304e+03 2.90000000e+01 5.25600000e+01 2.42714580e+02]
 [2.87105646e+03 5.70000000e+01 4.37000000e+01 2.48236050e+02]
 [3.10052643e+03 6.50000000e+01 7.52500000e+01 3.19674960e+02]
 [3.97029590e+03 8.70000000e+01 2.79000000e+01 5.32159270e+02]
 [4.69224902e+03 7.30000000e+01 1.14620000e+02 5.71365110e+02]
 [4.89624268e+03 7.20000000e+01 3.49960000e+02 4.58178380e+02]
 [3.51482275e+03 6.30000000e+01 0.00000000e+00 3.33602370e+02]
 [2.66176880e+03 7.60000000e+01 0.00000000e+00 3.24431060e+02]
 [4.69699231e+03 8.00000000e+01 3.29590000e+02 5.72917980e+02]
 [3.30994165e+03 7.00000000e+01 5.24200000e+01 3.63106760e+02]
 [2.72856445e+03 6.30000000e+01 8.05000000e+00 3.00691650e+02]
 [2.16050513e+03 4.10000000e+01 1.30200000e+01 2.43998840e+02]
 [4.00337817e+03 4.90000000e+01 0.00000000e+00 4.15297120e+02]
 [5.91329040e+02 2.10000000e+01 0.00000000e+00 4.02109400e+01]
 [3.28475629e+03 6.10000000e+01 5.74700000e+01 3.359606

In [31]:
print(X_test)

[[4.66967651e+03 9.20000000e+01 2.28260000e+02 5.49948790e+02]
 [3.50707837e+03 5.10000000e+01 1.01570000e+02 4.00207400e+02]
 [3.71180762e+03 6.90000000e+01 7.35000000e+00 3.02108470e+02]
 [4.97088010e+02 2.20000000e+01 0.00000000e+00 3.18560600e+01]
 [8.06528955e+03 1.06000000e+02 8.04469970e+02 8.12597110e+02]
 [3.55537109e+03 3.60000000e+01 1.05490000e+02 3.76486300e+02]
 [4.28893555e+03 7.20000000e+01 1.78260000e+02 4.39596500e+02]
 [3.98764040e+02 2.10000000e+01 0.00000000e+00 3.02823800e+01]
 [4.23248291e+03 7.20000000e+01 1.49690000e+02 4.35622680e+02]
 [3.82405908e+03 7.20000000e+01 1.17540000e+02 4.59525480e+02]
 [5.20533020e+02 2.10000000e+01 0.00000000e+00 3.67755600e+01]
 [2.92454370e+03 5.30000000e+01 1.63500000e+01 3.58570210e+02]
 [3.81605103e+03 7.20000000e+01 9.61100000e+01 3.98567630e+02]
 [5.13412793e+03 8.20000000e+01 1.15300000e+02 5.26858780e+02]
 [5.09784131e+03 9.10000000e+01 1.94999990e+02 5.00380270e+02]
 [4.26337363e+03 7.70000000e+01 1.42139990e+02 4.972252

In [32]:
print(y_train)

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1
 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [33]:
print(y_test)

[1 1 0 0 0 0 1 0 1 1 0 0 1 1 1 1 0 0 1 0 0 1 1 1 1 0]


In [34]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [35]:
print(X_train)

[[-3.25042300e-01 -6.17988620e-02 -3.52522688e-01 -8.10865075e-01]
 [-6.55847719e-01 -1.46391652e+00 -3.27477849e-01 -6.21759115e-01]
 [-3.12746439e-01 -1.97487668e-01 -3.72125188e-01 -5.91258293e-01]
 [-1.68270082e-01  1.64349148e-01 -2.13138331e-01 -1.96626881e-01]
 [ 3.79344601e-01  1.15940039e+00 -4.51744597e-01  9.77144992e-01]
 [ 8.33892780e-01  5.26185963e-01 -1.47449058e-02  1.19371963e+00]
 [ 9.62329024e-01  4.80956361e-01  1.17118115e+00  5.68471581e-01]
 [ 9.25746084e-02  7.38899437e-02 -5.92338363e-01 -1.19691308e-01]
 [-4.44515833e-01  6.61874769e-01 -5.92338363e-01 -1.70353994e-01]
 [ 8.36879198e-01  8.42793176e-01  1.06853258e+00  1.20229775e+00]
 [-3.64203753e-02  3.90497157e-01 -3.28183337e-01  4.32921285e-02]
 [-4.02460691e-01  7.38899437e-02 -5.51772778e-01 -3.01491449e-01]
 [-7.60115949e-01 -9.21161298e-01 -5.26727939e-01 -6.14664811e-01]
 [ 4.00173496e-01 -5.59324483e-01 -5.92338363e-01  3.31593776e-01]
 [-1.74808333e+00 -1.82575334e+00 -5.92338363e-01 -1.74039737e

In [36]:
print(X_test)

[[ 8.19680925e-01  1.38554840e+00  5.57910132e-01  1.07541502e+00]
 [ 8.76986771e-02 -4.68865279e-01 -8.05065060e-02  2.48237556e-01]
 [ 2.16598055e-01  3.45267555e-01 -5.55300220e-01 -2.93664878e-01]
 [-1.80741833e+00 -1.78052373e+00 -5.92338363e-01 -1.78655006e+00]
 [ 2.95758944e+00  2.01876283e+00  3.46154919e+00  2.52629490e+00]
 [ 1.18104208e-01 -1.14730931e+00 -6.07528299e-02  1.17201245e-01]
 [ 5.79962991e-01  4.80956361e-01  3.05949978e-01  4.65824528e-01]
 [-1.86932399e+00 -1.82575334e+00 -5.92338363e-01 -1.79524313e+00]
 [ 5.44419901e-01  4.80956361e-01  1.61979946e-01  4.43872987e-01]
 [ 2.87272584e-01  4.80956361e-01 -3.04327952e-05  5.75913015e-01]
 [-1.79265714e+00 -1.82575334e+00 -5.92338363e-01 -1.75937454e+00]
 [-2.79070392e-01 -3.78406075e-01 -5.09947393e-01  1.82320439e-02]
 [ 2.82230643e-01  4.80956361e-01 -1.08020555e-01  2.39179400e-01]
 [ 1.11210372e+00  9.33252380e-01 -1.13182477e-02  9.47864872e-01]
 [ 1.08925733e+00  1.34031880e+00  3.90306188e-01  8.01596518e

In [37]:
# logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [38]:
# classification model defined
model = LogisticRegression(random_state=0).fit(X, y)

In [39]:
# the intercept 𝑏₀
model.intercept_

array([-5.32564265])

In [40]:
# the slope 𝑏₁
model.coef_

array([[ 0.00038353,  0.0242062 , -0.00363653,  0.0039565 ]])

In [41]:
# the matrix of probabilities that the predicted output is equal to 0 or 1
model.predict_proba(X)

array([[0.92591884, 0.07408116],
       [0.85490462, 0.14509538],
       [0.81321533, 0.18678467],
       [0.8178952 , 0.1821048 ],
       [0.81689286, 0.18310714],
       [0.89805208, 0.10194792],
       [0.76329433, 0.23670567],
       [0.94992147, 0.05007853],
       [0.09711217, 0.90288783],
       [0.85137758, 0.14862242],
       [0.81291033, 0.18708967],
       [0.73368682, 0.26631318],
       [0.77988368, 0.22011632],
       [0.76615587, 0.23384413],
       [0.76618137, 0.23381863],
       [0.37635345, 0.62364655],
       [0.66860054, 0.33139946],
       [0.88303916, 0.11696084],
       [0.96041091, 0.03958909],
       [0.9146663 , 0.0853337 ],
       [0.85929203, 0.14070797],
       [0.80716739, 0.19283261],
       [0.8642341 , 0.1357659 ],
       [0.90376299, 0.09623701],
       [0.88869129, 0.11130871],
       [0.90181113, 0.09818887],
       [0.86339962, 0.13660038],
       [0.94719298, 0.05280702],
       [0.89679061, 0.10320939],
       [0.94587954, 0.05412046],
       [0.

In [42]:
# the actual prediction
model.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [43]:
# model accuracy
model.score(X, y)

0.7874015748031497

In [44]:
# more comprehensive model report
from sklearn.metrics import classification_report
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       0.83      0.91      0.86        95
           1       0.61      0.44      0.51        32

    accuracy                           0.79       127
   macro avg       0.72      0.67      0.69       127
weighted avg       0.77      0.79      0.77       127

