In [45]:
# import basic libraries
import pandas as pd
import numpy as np

In [46]:
# import dataset
df = pd.read_csv('MD3.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [47]:
print(X)

[[5.67473340e+03 8.60000000e+01 3.72669990e+02 5.99083680e+02]
 [6.20844824e+03 8.60000000e+01 2.36070000e+02 5.79928160e+02]
 [6.89275391e+03 9.90000000e+01 4.32600010e+02 7.21062770e+02]
 [5.47585791e+03 8.60000000e+01 3.08780000e+02 5.27788700e+02]
 [6.29310303e+03 8.60000000e+01 2.08320000e+02 6.40109250e+02]
 [5.47319629e+03 8.60000000e+01 2.75219990e+02 4.81662900e+02]
 [4.62748926e+03 5.10000000e+01 1.12470000e+02 5.10264400e+02]
 [6.02100586e+03 8.60000000e+01 1.67370000e+02 5.96450010e+02]
 [5.57281006e+03 8.60000000e+01 2.91830000e+02 4.72417760e+02]
 [5.66811426e+03 8.60000000e+01 2.63770000e+02 6.25582950e+02]
 [5.92843945e+03 8.60000000e+01 3.36130010e+02 5.57919620e+02]
 [6.23464856e+03 9.90000000e+01 3.97829990e+02 6.85674840e+02]
 [5.42744336e+03 8.10000000e+01 4.04669990e+02 5.76358150e+02]
 [3.80776831e+03 2.90000000e+01 3.30500000e+01 3.39164220e+02]
 [5.44932959e+03 8.60000000e+01 2.23880010e+02 6.19292910e+02]
 [6.18111865e+03 8.60000000e+01 3.55720000e+02 6.263511

In [48]:
print(y)

['W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W'
 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W'
 'W' 'W' 'W' 'W' 'W' 'W']


In [49]:
# encode categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [50]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [51]:
# split into training and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [52]:
print(X_train)

[[6.86575244e+03 9.80000000e+01 2.44860000e+02 6.93290470e+02]
 [5.93080908e+03 8.40000000e+01 2.99460000e+02 6.26750980e+02]
 [4.92791821e+03 9.10000000e+01 4.28600000e+01 6.08245640e+02]
 [6.45582056e+03 1.09000000e+02 3.16140000e+02 6.20247950e+02]
 [2.19525513e+03 3.70000000e+01 3.51800000e+01 2.40741590e+02]
 [4.96044287e+03 6.90000000e+01 1.79540010e+02 5.36180360e+02]
 [5.10561035e+03 6.90000000e+01 2.59280000e+02 4.94085300e+02]
 [5.79993506e+03 8.40000000e+01 2.32970000e+02 5.15067500e+02]
 [2.34974316e+03 3.80000000e+01 3.38400000e+01 2.62265840e+02]
 [4.82433997e+03 6.60000000e+01 2.44970000e+02 4.45184800e+02]
 [1.66636511e+03 3.20000000e+01 4.35000000e+00 1.64729540e+02]
 [3.10031421e+03 5.00000000e+01 1.02550000e+02 3.08699050e+02]
 [5.87594589e+03 1.06000000e+02 8.51700000e+01 6.75653640e+02]
 [5.68434494e+03 8.90000000e+01 1.32870000e+02 5.07998260e+02]
 [4.89954443e+03 6.90000000e+01 9.76900000e+01 4.81751950e+02]
 [5.31791748e+03 8.40000000e+01 9.44100000e+01 5.460714

In [53]:
print(X_test)

[[6015.67383   84.       331.29999  598.07001]
 [5067.05225   82.       246.55     502.82941]
 [6843.2363    98.       470.28     674.94891]
 [5791.01392   85.       282.49     612.53225]
 [2025.78406   34.        12.65     183.99835]
 [3832.00049   71.        62.49     361.28055]
 [6531.52783  114.        54.23     688.61864]
 [5449.32959   86.       223.88001  619.29291]
 [5770.97461   93.       354.40001  553.33971]
 [6106.38989   99.       252.49     662.08669]
 [6234.64856   99.       397.82999  685.67484]
 [6293.10303   86.       208.32     640.10925]
 [5314.65674   74.       363.67999  595.20038]
 [1658.25232   27.         9.97     186.97797]
 [4869.36987   81.        95.17     530.10109]
 [5701.27441   86.       239.84     556.0406 ]
 [6639.16724  102.       137.8      715.97118]
 [1939.82446   27.        25.76     219.93198]
 [3598.15503   51.       118.47     373.87421]
 [4624.99567   66.        97.44     439.99864]
 [2987.56543   45.        93.35     356.56213]
 [4786.23096 

In [54]:
print(y_train)

[0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1
 0 1 0 0 1 1 0 1 1 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1
 1 0 0 0 1 0 0 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 0 1 1 0
 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [55]:
print(y_test)

[0 0 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0]


In [56]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [57]:
print(X_train)

[[ 1.12365656e+00  9.95234413e-01  2.43437589e-01  8.57714312e-01]
 [ 5.52840777e-01  4.05282258e-01  5.23638534e-01  5.01037547e-01]
 [-5.94593531e-02  7.00258335e-01 -7.93203268e-01  4.01841944e-01]
 [ 8.73378741e-01  1.45876825e+00  6.09238383e-01  4.66178853e-01]
 [-1.72784622e+00 -1.57527141e+00 -8.32616148e-01 -1.56811838e+00]
 [-3.96019049e-02 -2.26809337e-01 -9.17771161e-02  1.55448607e-02]
 [ 4.90279447e-02 -2.26809337e-01  3.17439377e-01 -2.10100539e-01]
 [ 4.72937587e-01  4.05282258e-01  1.82419471e-01 -9.76280326e-02]
 [-1.63352585e+00 -1.53313197e+00 -8.39492875e-01 -1.45274029e+00]
 [-1.22697510e-01 -3.53227656e-01  2.44002096e-01 -4.72225664e-01]
 [-2.05075217e+00 -1.78596860e+00 -9.90832176e-01 -1.97557164e+00]
 [-1.17527584e+00 -1.02745869e+00 -4.86881027e-01 -1.20384077e+00]
 [ 5.19344871e-01  1.33234993e+00 -5.76073196e-01  7.63174250e-01]
 [ 4.02365756e-01  6.15979456e-01 -3.31282261e-01 -1.35521825e-01]
 [-7.67825432e-02 -2.26809337e-01 -5.11821990e-01 -2.76211947e

In [58]:
print(X_test)

[[ 0.60465369  0.40528226  0.68703771  0.34729673]
 [ 0.02548687  0.32100338  0.25211048 -0.16322881]
 [ 1.10990967  0.99523441  1.4002672   0.75939663]
 [ 0.46749092  0.4474217   0.43655044  0.42481979]
 [-1.83131427 -1.70168972 -0.94823753 -1.87228355]
 [-0.72855565 -0.14253046 -0.69246436 -0.92198409]
 [ 0.91960069  1.66946545 -0.73485373  0.83267154]
 [ 0.25888062  0.48956114  0.13577068  0.46105948]
 [ 0.45525621  0.78453721  0.80558437  0.10752545]
 [ 0.66003903  1.03737385  0.28259387  0.69045028]
 [ 0.73834546  1.03737385  1.02846205  0.81689166]
 [ 0.77403397  0.48956114  0.0559185   0.57264291]
 [ 0.17665811 -0.01611214  0.85320816  0.33191443]
 [-2.05570532 -1.9966658  -0.96199098 -1.85631167]
 [-0.09520517  0.27886394 -0.52475434 -0.01704232]
 [ 0.41270179  0.48956114  0.21767552  0.12200324]
 [ 0.98531833  1.16379217 -0.30598207  0.97929147]
 [-1.88379563 -1.9966658  -0.88095851 -1.67966574]
 [-0.87132652 -0.98531925 -0.40518141 -0.85447732]
 [-0.24440421 -0.35322766 -0.51

In [59]:
# logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [60]:
# classification model defined
model = LogisticRegression(random_state=0).fit(X, y)

In [61]:
# the intercept 𝑏₀
model.intercept_

array([-0.00037217])

In [62]:
# the slope 𝑏₁
model.coef_

array([[ 6.63601842e-04,  2.57758062e-02, -2.87763090e-06,
        -1.14510239e-02]])

In [63]:
# the matrix of probabilities that the predicted output is equal to 0 or 1
model.predict_proba(X)

array([[0.70663221, 0.29336779],
       [0.57570482, 0.42429518],
       [0.75633223, 0.24366777],
       [0.5484656 , 0.4515344 ],
       [0.71870435, 0.28129565],
       [0.41774314, 0.58225686],
       [0.81128311, 0.18871689],
       [0.64988806, 0.35011194],
       [0.37660878, 0.62339122],
       [0.76613352, 0.23386648],
       [0.55952823, 0.44047177],
       [0.7620709 , 0.2379291 ],
       [0.7133941 , 0.2866059 ],
       [0.647919  , 0.352081  ],
       [0.77896582, 0.22103418],
       [0.70166448, 0.29833552],
       [0.43126169, 0.56873831],
       [0.77758785, 0.22241215],
       [0.43823365, 0.56176635],
       [0.66001663, 0.33998337],
       [0.67819956, 0.32180044],
       [0.67381733, 0.32618267],
       [0.55458361, 0.44541639],
       [0.8046867 , 0.1953133 ],
       [0.59651651, 0.40348349],
       [0.96303222, 0.03696778],
       [0.46751845, 0.53248155],
       [0.48010115, 0.51989885],
       [0.45375954, 0.54624046],
       [0.57945406, 0.42054594],
       [0.

In [64]:
# the actual prediction
model.predict(X)

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [65]:
# model accuracy
model.score(X, y)

0.6842105263157895

In [66]:
# more comprehensive model report
from sklearn.metrics import classification_report
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       0.71      0.92      0.80       118
           1       0.47      0.17      0.25        53

    accuracy                           0.68       171
   macro avg       0.59      0.54      0.53       171
weighted avg       0.64      0.68      0.63       171

