In [67]:
# import basic libraries
import pandas as pd
import numpy as np

In [68]:
# import dataset
df = pd.read_csv('MD4.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [69]:
print(X)

[[7.70909052e+03 1.04000000e+02 4.80479990e+02 8.23673460e+02]
 [7.04249463e+03 9.30000000e+01 2.70100000e+01 7.04649350e+02]
 [5.44495215e+03 6.30000000e+01 7.63340020e+02 5.87135250e+02]
 [6.85619873e+03 9.30000000e+01 3.66599990e+02 6.68855160e+02]
 [5.77553857e+03 7.20000000e+01 2.94200000e+01 6.52998050e+02]
 [6.34903711e+03 9.30000000e+01 3.63150010e+02 6.32725590e+02]
 [6.87862988e+03 9.30000000e+01 3.69099990e+02 6.70708010e+02]
 [7.10119598e+03 1.04000000e+02 1.55390000e+02 6.30325430e+02]
 [6.39517432e+03 9.30000000e+01 3.11969990e+02 6.45032710e+02]
 [5.95775439e+03 9.30000000e+01 2.36340010e+02 6.64409790e+02]
 [6.82034033e+03 9.30000000e+01 3.01100000e+01 6.69627560e+02]
 [6.26380322e+03 9.30000000e+01 1.37840000e+02 7.20429140e+02]
 [6.53868848e+03 9.70000000e+01 4.53370020e+02 6.59978200e+02]
 [6.19533789e+03 9.30000000e+01 3.09550000e+02 5.74710270e+02]
 [8.28798584e+03 1.07000000e+02 4.49479990e+02 8.84337490e+02]
 [8.20210352e+03 9.70000000e+01 2.40910000e+02 8.175124

In [70]:
print(y)

['NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'W' 'W' 'W' 'W' 'W' 'W' 'W'
 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'W' 'W' 'W' 'W' 'W' 'W'
 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW

In [71]:
# encode categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [72]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [73]:
# split into training and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [74]:
print(X_train)

[[7.87223062e+03 1.08000000e+02 2.69720010e+02 6.89486100e+02]
 [7.91948975e+03 1.20000000e+02 3.67400000e+02 8.49272670e+02]
 [6.09857324e+03 9.50000000e+01 3.30400000e+01 7.59018010e+02]
 [6.75522559e+03 9.50000000e+01 1.08200000e+01 8.46881290e+02]
 [7.54156543e+03 1.05000000e+02 3.76390000e+02 7.59136920e+02]
 [9.47880566e+03 1.08000000e+02 7.95099980e+02 9.84634750e+02]
 [7.63708212e+03 1.05000000e+02 5.25180000e+02 9.09192710e+02]
 [6.31863233e+03 9.00000000e+01 2.94249990e+02 6.46542740e+02]
 [5.31302686e+03 8.80000000e+01 6.95569990e+02 5.65509460e+02]
 [7.63024023e+03 9.30000000e+01 4.50230000e+02 8.27730440e+02]
 [6.19844531e+03 8.80000000e+01 5.66259990e+02 7.99340880e+02]
 [6.88191748e+03 1.00000000e+02 2.44570000e+02 7.46696170e+02]
 [4.69843701e+03 5.90000000e+01 2.39130000e+02 5.00352750e+02]
 [8.28798584e+03 1.07000000e+02 4.49479990e+02 8.84337490e+02]
 [6.01553516e+03 8.90000000e+01 4.13799990e+02 6.32325130e+02]
 [8.57616113e+03 1.29000000e+02 4.69270000e+02 1.027701

In [75]:
print(X_test)

[[6673.46855   89.       509.48     693.53935]
 [7321.25439  102.       180.92     722.80829]
 [7997.81085  103.       469.40002  818.73849]
 [7370.11768  106.        73.92     942.31189]
 [7199.14669   89.       353.13999  701.45807]
 [6510.62671  107.       122.45     695.91036]
 [3801.74512   54.        96.64     442.89835]
 [6053.62012   92.       373.86001  582.77832]
 [8420.875    118.       112.83     965.98894]
 [8070.64941  102.       688.73     790.92261]
 [6424.83252   95.        96.43     766.37238]
 [5775.53857   72.        29.42     652.99805]
 [7795.9541   103.       286.50999  889.9115 ]
 [8532.32629  117.       531.43999  795.43503]
 [8465.6748   109.       366.23     741.49397]
 [7658.17822  120.       396.42     812.60679]
 [7307.22363  102.       444.52999  729.65613]
 [1885.00903   28.        18.39     195.60031]
 [7520.33931   89.       562.51001  803.96595]
 [8104.89243   99.       467.8      740.27045]
 [5775.66943   99.       106.15     580.04297]
 [8910.17478 

In [76]:
print(y_train)

[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0
 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [77]:
print(y_test)

[0 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0]


In [78]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [79]:
print(X_train)

[[ 5.72624286e-01  5.81966002e-01 -4.31416595e-01 -1.34649679e-01]
 [ 5.97854779e-01  1.08745651e+00 -6.35434282e-03  6.37710094e-01]
 [-3.74288014e-01  3.43512892e-02 -1.46134850e+00  2.01446466e-01]
 [-2.37173829e-02  3.43512892e-02 -1.55804060e+00  6.26150889e-01]
 [ 3.96090227e-01  4.55593376e-01  3.27663578e-02  2.02021241e-01]
 [ 1.43033541e+00  5.81966002e-01  1.85481616e+00  1.29200930e+00]
 [ 4.47084252e-01  4.55593376e-01  6.80237886e-01  9.27345378e-01]
 [-2.56803847e-01 -1.76269754e-01 -3.24672434e-01 -3.42224845e-01]
 [-7.93672015e-01 -2.60518171e-01  1.42170349e+00 -7.33915122e-01]
 [ 4.43431534e-01 -4.98971281e-02  3.54086995e-01  5.33581494e-01]
 [-3.20968758e-01 -2.60518171e-01  8.59000733e-01  3.96354979e-01]
 [ 4.39203188e-02  2.44972332e-01 -5.40858865e-01  1.41886432e-01]
 [-1.12178651e+00 -1.48212022e+00 -5.64531458e-01 -1.04886288e+00]
 [ 7.94585830e-01  5.39841793e-01  3.50823267e-01  8.07202790e-01]
 [-4.18620014e-01 -2.18393963e-01  1.95558907e-01 -4.10948456e

In [80]:
print(X_test)

[[-0.06736547 -0.21839396  0.61191809 -0.1150575 ]
 [ 0.27847155  0.32922075 -0.81783691  0.02641967]
 [ 0.6396685   0.37134496  0.43750686  0.49011714]
 [ 0.30455847  0.49771758 -1.28345592  1.08743344]
 [ 0.21328124 -0.21839396 -0.06840791 -0.07678081]
 [-0.15430274  0.53984179 -1.07227377 -0.10359676]
 [-1.60050838 -1.69274127 -1.18458804 -1.32658001]
 [-0.39828739 -0.09202134  0.0217569  -0.6504427 ]
 [ 0.8655321   1.00320809 -1.11413596  1.20188111]
 [ 0.67855523  0.32922075  1.39193873  0.35566362]
 [-0.20010616  0.03435129 -1.18550187  0.23699526]
 [-0.54674832 -0.93450551 -1.47710122 -0.31102184]
 [ 0.53190212  0.37134496 -0.35835366  0.83414586]
 [ 0.92503322  0.96108388  0.70747873  0.37747529]
 [ 0.88944962  0.62409021 -0.01144569  0.11674058]
 [ 0.45834694  1.08745651  0.1199285   0.46047836]
 [ 0.27098087  0.32922075  0.32928295  0.05952005]
 [-2.6238069  -2.78797069 -1.52509914 -2.52194366]
 [ 0.38475812 -0.21839396  0.8426824   0.41871116]
 [ 0.69683674  0.20284812  0.43

In [81]:
# logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [82]:
# classification model defined
model = LogisticRegression(random_state=0).fit(X, y)

In [83]:
# the intercept 𝑏₀
model.intercept_

array([-0.0004701])

In [84]:
# the slope 𝑏₁
model.coef_

array([[-0.00017087,  0.00231425,  0.00091774, -0.00100474]])

In [85]:
# the matrix of probabilities that the predicted output is equal to 0 or 1
model.predict_proba(X)

array([[0.81208852, 0.18791148],
       [0.84181231, 0.15818769],
       [0.66248892, 0.33751108],
       [0.78454036, 0.21545964],
       [0.80996537, 0.19003463],
       [0.76360248, 0.23639752],
       [0.78511453, 0.21488547],
       [0.81212128, 0.18787872],
       [0.7755207 , 0.2244793 ],
       [0.77797214, 0.22202786],
       [0.83142822, 0.16857178],
       [0.81043874, 0.18956126],
       [0.75772812, 0.24227188],
       [0.75715988, 0.24284012],
       [0.83821564, 0.16178436],
       [0.85541886, 0.14458114],
       [0.84930174, 0.15069826],
       [0.87050389, 0.12949611],
       [0.81743677, 0.18256323],
       [0.83269869, 0.16730131],
       [0.85564843, 0.14435157],
       [0.642278  , 0.357722  ],
       [0.80021154, 0.19978846],
       [0.84555996, 0.15444004],
       [0.80429812, 0.19570188],
       [0.80353819, 0.19646181],
       [0.82109085, 0.17890915],
       [0.86930604, 0.13069396],
       [0.84747018, 0.15252982],
       [0.66206124, 0.33793876],
       [0.

In [86]:
# the actual prediction
model.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
# model accuracy
model.score(X, y)

0.8285714285714286

In [88]:
# more comprehensive model report
from sklearn.metrics import classification_report
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       0.83      1.00      0.91       173
           1       1.00      0.03      0.05        37

    accuracy                           0.83       210
   macro avg       0.91      0.51      0.48       210
weighted avg       0.86      0.83      0.76       210

