In [89]:
# import basic libraries
import pandas as pd
import numpy as np

In [90]:
# import dataset
df = pd.read_csv('MD5.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [91]:
print(X)

[[8.41620801e+03 1.02000000e+02 6.71050010e+02 8.59826110e+02]
 [1.10229111e+04 1.13000000e+02 6.55410000e+02 1.07056396e+03]
 [8.65426074e+03 1.02000000e+02 1.83830000e+02 8.92164980e+02]
 [8.13876953e+03 1.02000000e+02 4.54500000e+02 7.76338380e+02]
 [1.30771619e+03 1.50000000e+01 1.72710010e+02 1.38181880e+02]
 [8.38416992e+03 1.02000000e+02 5.64390010e+02 8.30125000e+02]
 [7.77839648e+03 1.02000000e+02 4.85059990e+02 7.60873350e+02]
 [3.88739575e+03 4.40000000e+01 7.54700000e+01 3.44214390e+02]
 [9.91977051e+03 1.19000000e+02 2.47500000e+02 1.02730865e+03]
 [7.24009521e+03 9.50000000e+01 2.11099990e+02 6.54183470e+02]
 [8.60194238e+03 1.02000000e+02 3.81090010e+02 1.00599127e+03]
 [8.38416992e+03 1.02000000e+02 5.64390010e+02 8.30125000e+02]
 [7.62288818e+03 1.02000000e+02 4.55410010e+02 8.33964050e+02]
 [5.47362012e+03 7.30000000e+01 3.32600000e+02 6.43447020e+02]
 [8.31963477e+03 1.02000000e+02 2.45400010e+02 8.33857970e+02]
 [1.10996045e+04 1.13000000e+02 6.33340020e+02 1.064951

In [92]:
print(y)

['NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W'
 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW']


In [93]:
# encode categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [94]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [95]:
# split into training and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [96]:
print(X_train)

[[ 8654.26074   102.        183.83      892.16498]
 [ 6260.53271    92.        374.46001   605.60413]
 [ 4354.35986    73.        619.09003   436.17703]
 [ 1067.526      28.          0.        157.81137]
 [ 7614.19727   102.        224.        768.33698]
 [ 1745.09412    17.        104.62      152.1259 ]
 [ 7206.59473    99.        295.12      922.39594]
 [ 6893.4646    102.        298.53999   679.31699]
 [ 8100.14404   101.        292.41      832.6944 ]
 [11615.46326    93.        589.51999  1244.26883]
 [ 7585.72119    99.        516.67998   966.51874]
 [ 4443.15222    82.         35.03      524.31793]
 [ 3455.45337    28.        586.01998   311.6749 ]
 [ 6656.25098    92.        460.21001   679.96729]
 [ 6904.55762    92.        358.91999   748.26141]
 [ 4501.69507    82.         84.1       516.34857]
 [ 7636.28271   101.        376.56      776.45715]
 [ 7689.13818   101.        259.15001   875.31934]
 [ 9444.37292   136.        725.02999  1026.70987]
 [ 5641.83521    97.        743

In [97]:
print(X_test)

[[2.54761914e+03 4.10000000e+01 9.89000000e+01 3.59370570e+02]
 [7.67818115e+03 9.90000000e+01 5.40740000e+02 7.20774780e+02]
 [8.20252364e+03 1.04000000e+02 5.14570010e+02 9.43083800e+02]
 [3.46817114e+03 5.00000000e+01 2.77000000e+00 3.74805180e+02]
 [9.67422510e+03 1.36000000e+02 6.65839980e+02 9.98786620e+02]
 [1.06241660e+04 1.13000000e+02 4.43680010e+02 1.23894470e+03]
 [3.93781519e+03 6.20000000e+01 1.65580000e+02 4.05365020e+02]
 [7.66023535e+03 9.90000000e+01 5.64920010e+02 8.39068180e+02]
 [2.97617725e+03 5.60000000e+01 1.05760000e+02 3.53111720e+02]
 [6.97600000e+03 1.08690000e+02 3.18000000e+02 0.00000000e+00]
 [6.89906287e+03 1.02000000e+02 2.69480000e+02 6.14657040e+02]
 [1.22465568e+04 9.30000000e+01 6.80960000e+02 1.06824580e+03]
 [6.78610486e+03 1.02000000e+02 3.69089990e+02 6.86596610e+02]
 [3.29839917e+03 3.60000000e+01 8.67270030e+02 3.93779850e+02]
 [6.32935352e+03 9.20000000e+01 4.54159990e+02 6.27779910e+02]
 [3.85945435e+03 7.30000000e+01 7.52429980e+02 3.818888

In [98]:
print(y_train)

[0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 1]


In [99]:
print(y_test)

[0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


In [100]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [101]:
print(X_train)

[[ 0.84099476  0.44129692 -0.8546072   0.77425218]
 [-0.14973903  0.03776632 -0.00442038 -0.36046922]
 [-0.93867988 -0.7289418   1.08659996 -1.03136531]
 [-2.29905888 -2.54482946 -1.6744668  -2.13363546]
 [ 0.41052563  0.44129692 -0.67545385  0.28391904]
 [-2.018622   -2.98871311 -1.20787424 -2.15614874]
 [ 0.24182409  0.32023774 -0.35826724  0.8939605 ]
 [ 0.11222349  0.44129692 -0.3430145  -0.06858161]
 [ 0.61165286  0.40094386 -0.37035352  0.53876105]
 [ 2.06659906  0.07811938  0.95472115  2.16851024]
 [ 0.39873974  0.32023774  0.62986351  1.06867762]
 [-0.90192985 -0.36576427 -1.51823723 -0.68234567]
 [-1.31072592 -2.54482946  0.93911153 -1.52436787]
 [ 0.01404377  0.03776632  0.37801426 -0.06600656]
 [ 0.11681475  0.03776632 -0.07372699  0.20442396]
 [-0.8776997  -0.36576427 -1.29939096 -0.71390268]
 [ 0.41966652  0.40094386  0.00494532  0.31607323]
 [ 0.44154273  0.40094386 -0.51868906  0.70754695]
 [ 1.16801221  1.81330093  1.55907939  1.30702198]
 [-0.4058101   0.23953162  1.64

In [102]:
print(X_test)

[[-1.68646703 -2.02023969 -1.23338475 -1.33550293]
 [ 0.43700775  0.32023774  0.73716829  0.09558262]
 [ 0.65402648  0.52200303  0.6204533   0.97588013]
 [-1.30546219 -1.65706216 -1.66211293 -1.27438508]
 [ 1.26314512  1.81330093  1.29509909  1.19645171]
 [ 1.65631366  0.88518057  0.30429246  2.14742779]
 [-1.11108246 -1.17282545 -0.936      -1.15337447]
 [ 0.42958021  0.32023774  0.84500821  0.56399989]
 [-1.50909225 -1.41494381 -1.20278997 -1.36028667]
 [ 0.14638385  0.71125888 -0.25622521 -2.75853568]
 [ 0.11454054  0.44129692 -0.47261855 -0.32462157]
 [ 2.32780069  0.07811938  1.36253256  1.47149563]
 [ 0.06778865  0.44129692 -0.02837002 -0.03975583]
 [-1.37572867 -2.22200499  2.19345279 -1.19924933]
 [-0.12125496  0.03776632  0.3510319  -0.27265774]
 [-1.14351502 -0.7289418   1.68128003 -1.24633522]
 [ 0.51443723  0.32023774  0.95173308  0.61986983]
 [-1.5555021  -1.41494381 -1.23316175 -1.55927577]
 [-0.74679256 -0.36576427 -1.49870296 -0.33080352]
 [ 0.81934085  0.44129692  0.02

In [103]:
# logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [104]:
# classification model defined
model = LogisticRegression(random_state=0).fit(X, y)

In [105]:
# the intercept 𝑏₀
model.intercept_

array([-0.00140556])

In [106]:
# the slope 𝑏₁
model.coef_

array([[ 0.00117998, -0.07862793, -0.00212098, -0.00228142]])

In [107]:
# the matrix of probabilities that the predicted output is equal to 0 or 1
model.predict_proba(X)

array([[0.81387668, 0.18612332],
       [0.42850731, 0.57149269],
       [0.55845514, 0.44154486],
       [0.76005884, 0.23994116],
       [0.57915614, 0.42084386],
       [0.77192608, 0.22807392],
       [0.83310161, 0.16689839],
       [0.45495988, 0.54504012],
       [0.62753456, 0.37246544],
       [0.70434839, 0.29565161],
       [0.72605525, 0.27394475],
       [0.77192608, 0.22807392],
       [0.86933939, 0.13066061],
       [0.81090301, 0.18909699],
       [0.65187999, 0.34812001],
       [0.39220434, 0.60779566],
       [0.75512983, 0.24487017],
       [0.52937572, 0.47062428],
       [0.73150687, 0.26849313],
       [0.7798592 , 0.2201408 ],
       [0.84686825, 0.15313175],
       [0.62184594, 0.37815406],
       [0.82492069, 0.17507931],
       [0.81791137, 0.18208863],
       [0.88258681, 0.11741319],
       [0.87516503, 0.12483497],
       [0.73742441, 0.26257559],
       [0.66849569, 0.33150431],
       [0.17794671, 0.82205329],
       [0.77419807, 0.22580193],
       [0.

In [108]:
# the actual prediction
model.predict(X)

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [109]:
# model accuracy
model.score(X, y)

0.826530612244898

In [110]:
# more comprehensive model report
from sklearn.metrics import classification_report
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       0.85      0.96      0.90        80
           1       0.57      0.22      0.32        18

    accuracy                           0.83        98
   macro avg       0.71      0.59      0.61        98
weighted avg       0.80      0.83      0.79        98

