In [1]:
# import basic libraries
import pandas as pd
import numpy as np

In [2]:
# import dataset
df = pd.read_csv('MD0.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [3]:
print(X)

[[ 4955.06201    41.        628.92999   435.03461]
 [ 4641.57471    72.        198.17      678.20953]
 [12786.99707    98.        750.          0.     ]
 ...
 [ 5654.36597    46.       1014.54998   190.85849]
 [ 5310.00439    82.        828.84997   612.74957]
 [10203.02588    98.        392.27        0.     ]]


In [4]:
print(y)

['NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W'
 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'W'
 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W'
 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW'
 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'NW' 'W' 'W' 'W' 'W' '

In [5]:
# encode categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [6]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [7]:
# split into training and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [8]:
print(X_train)

[[12266.54492    96.        971.89001     0.     ]
 [ 6097.46729    71.        874.75001   602.92651]
 [ 8238.4895     69.        860.96001     0.     ]
 ...
 [12059.42188   101.        873.10999     0.     ]
 [10642.01611    99.        543.22        0.     ]
 [ 6589.90771    94.        222.62      769.40204]]


In [9]:
print(X_test)

[[3.24523688e+03 2.40000000e+01 6.99920000e+02 6.00761200e+01]
 [1.09387261e+04 9.50000000e+01 7.92490010e+02 0.00000000e+00]
 [1.15286763e+04 9.20000000e+01 1.26296998e+03 0.00000000e+00]
 [1.10325806e+04 1.00000000e+02 1.07993001e+03 0.00000000e+00]
 [1.12676187e+04 9.60000000e+01 1.35781000e+03 0.00000000e+00]
 [1.14023403e+04 9.80000000e+01 1.08715999e+03 0.00000000e+00]
 [1.05762129e+04 9.60000000e+01 8.03540020e+02 0.00000000e+00]
 [1.07804565e+04 9.80000000e+01 8.49609990e+02 0.00000000e+00]
 [1.16904380e+04 9.40000000e+01 1.13777002e+03 0.00000000e+00]
 [1.28983687e+04 1.00000000e+02 8.17449990e+02 0.00000000e+00]
 [1.20386982e+04 9.90000000e+01 7.34710010e+02 0.00000000e+00]
 [1.08745278e+04 9.60000000e+01 6.65889980e+02 0.00000000e+00]
 [1.40908008e+03 1.00000000e+01 5.69259990e+02 1.19784400e+02]
 [5.31000439e+03 8.20000000e+01 8.28849970e+02 6.12749570e+02]
 [4.51510999e+03 4.00000000e+01 1.04190999e+03 1.82795760e+02]
 [1.14410444e+04 9.90000000e+01 8.91270020e+02 0.000000

In [10]:
print(y_train)

[1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0
 0 0 0 1 1 1 0 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 1 1 1
 0 0 0 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 1 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0
 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0
 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0
 0 1 0 1 1 0 0 0 0 1 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 1 0 1 0 0 0
 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 1 0
 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1]


In [11]:
print(y_test)

[0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 1
 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 0
 0 0 0 1 0 0 0 0 0 1 1 0]


In [12]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
print(X_train)

[[ 1.24484111  0.78035428  0.99466895 -0.60629244]
 [-0.36387125  0.02595316  0.66278824  1.73659269]
 [ 0.1944438  -0.03439893  0.61567443 -0.60629244]
 ...
 [ 1.19082957  0.93123451  0.65718508 -0.60629244]
 [ 0.82121221  0.87088242 -0.46989051 -0.60629244]
 [-0.2354574   0.72000219 -1.56522668  2.3834925 ]]


In [14]:
print(X_test)

[[-1.1076483  -1.39232094  0.0654781  -0.37284534]
 [ 0.89858536  0.75017824  0.38174534 -0.60629244]
 [ 1.05242687  0.6596501   1.98914935 -0.60629244]
 [ 0.92305983  0.90105846  1.36378972 -0.60629244]
 [ 0.98435079  0.78035428  2.31317213 -0.60629244]
 [ 1.0194822   0.84070637  1.38849108 -0.60629244]
 [ 0.80405268  0.78035428  0.41949792 -0.60629244]
 [ 0.85731337  0.84070637  0.57689687 -0.60629244]
 [ 1.09460952  0.72000219  1.56140124 -0.60629244]
 [ 1.40960199  0.90105846  0.4670216  -0.60629244]
 [ 1.18542546  0.87088242  0.18433884 -0.60629244]
 [ 0.88184437  0.78035428 -0.05078613 -0.60629244]
 [-1.5864635  -1.81478557 -0.38092438 -0.1408276 ]
 [-0.56921821  0.35788966  0.50596986  1.77476368]
 [-0.77650308 -0.90950422  1.23389358  0.10402542]
 [ 1.02957508  0.87088242  0.71922918 -0.60629244]
 [-1.34874658 -1.45267303 -1.60294502 -0.60629244]
 [-1.00954793 -1.06038445 -0.14655114  1.06387087]
 [ 1.1339959   0.84070637  0.86531952 -0.60629244]
 [ 0.20414699  1.95722003 -0.25

In [15]:
# logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [16]:
# classification model defined
model = LogisticRegression(random_state=0).fit(X, y)

In [17]:
# the intercept 𝑏₀
model.intercept_

array([-2.00698381])

In [18]:
# the slope 𝑏₁
model.coef_

array([[-0.00018644,  0.01884666,  0.00166295, -0.00012402]])

In [19]:
# the matrix of probabilities that the predicted output is equal to 0 or 1
model.predict_proba(X)

array([[0.76245302, 0.23754698],
       [0.78073832, 0.21926168],
       [0.7853011 , 0.2146989 ],
       [0.81922391, 0.18077609],
       [0.68071955, 0.31928045],
       [0.75940725, 0.24059275],
       [0.69748683, 0.30251317],
       [0.82126265, 0.17873735],
       [0.75378515, 0.24621485],
       [0.66172437, 0.33827563],
       [0.70111675, 0.29888325],
       [0.7247278 , 0.2752722 ],
       [0.60211315, 0.39788685],
       [0.7427679 , 0.2572321 ],
       [0.59776403, 0.40223597],
       [0.76913115, 0.23086885],
       [0.77780424, 0.22219576],
       [0.69307031, 0.30692969],
       [0.73175833, 0.26824167],
       [0.7101184 , 0.2898816 ],
       [0.68871656, 0.31128344],
       [0.83436052, 0.16563948],
       [0.6727973 , 0.3272027 ],
       [0.79675761, 0.20324239],
       [0.74593133, 0.25406867],
       [0.50395186, 0.49604814],
       [0.71141285, 0.28858715],
       [0.75820813, 0.24179187],
       [0.79676613, 0.20323387],
       [0.64759237, 0.35240763],
       [0.

In [20]:
# the actual prediction
model.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [21]:
# model accuracy
model.score(X, y)

0.7149532710280374

In [22]:
# more comprehensive model report
from sklearn.metrics import classification_report
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       0.72      0.99      0.83       305
           1       0.60      0.02      0.05       123

    accuracy                           0.71       428
   macro avg       0.66      0.51      0.44       428
weighted avg       0.68      0.71      0.61       428

